name: 'pku-grade-watcher'
description: 'Watch PKU grade updates and notify you.'
author: 'zhuozhiyongde'
branding:
  icon: 'code'
  color: 'red'

inputs:
  api-token:
    description: 'Personal GitHub API token to avoid rate limits'
    required: true
  username:
    description: 'PKU student ID'
    required: true
  password:
    description: 'PKU password'
    required: true
  bark:
    description: 'Bark key'
    default: ''
  git-name:
    description: 'Name used for Git commits'
    default: 'Github Action'
  git-email:
    description: 'Email used for Git commits'
    default: 'actions@users.noreply.github.com'
  git-message:
    description: 'Commit message'
    default: 'chore(updates): updated data'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        git config --global user.name "${{ inputs.git-name }}"
        git config --global user.email "${{ inputs.git-email }}"
        git clone https://github.com/zhuozhiyongde/pku-grade-watcher.git
        cd pku-grade-watcher
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cd ..
      shell: bash

    - name: Run Stargazer
      run: python pku-grade-watcher/main.py
      shell: bash
      env:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
        bark: ${{ inputs.bark }}

    - name: Commit and push changes
      run: |
        git add data.json
        if ! git diff-index --quiet HEAD --; then
          git commit -m "${{ inputs.git-message }}"
          git push
        else
          echo "No changes to commit."
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.api-token }}
